In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/BankChurners.csv')
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [ ]:
## 어떤 열들이 있는지 확인
df.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [ ]:
df.drop(['CLIENTNUM', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'], axis=1, inplace=True)

In [ ]:
df.info()

## 데이터 정보 살펴보기

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition_Flag            10127 non-null  object
 1   Customer_Age              10127 non-null  int64
 2   Gender                    10127 non-null  object
 3   Dependent_count           10127 non-null  int64
 4   Education_Level           10127 non-null  object
 5   Marital_Status            10127 non-null  object
 6   Income_Category           10127 non-null  object
 7   Card_Category             10127 non-null  object
 8   Months_on_book            10127 non-null  int64
 9   Total_Relationship_Count  10127 non-null  int64
 10  Months_Inactive_12_mon    10127 non-null  int64
 11  Contacts_Count_12_mon     10127 non-null  int64
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  int64
 14  Avg_Open_To_Buy           10127 non-null  float64
 15  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 16  Total_Trans_Amt           10127 non-null  int64
 17  Total_Trans_Ct            10127 non-null  int64
 18  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 19  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(9), object(6)
memory usage: 1.5+ MB

In [ ]:
## Dtype이 object인 열들 보기

In [3]:
df.Gender.value_counts()

F    5358
M    4769
Name: Gender, dtype: int64

In [4]:
df.Education_Level.value_counts()

Graduate         3128
High School      2013
Unknown          1519
Uneducated       1487
College          1013
Post-Graduate     516
Doctorate         451
Name: Education_Level, dtype: int64

In [5]:
df.Marital_Status.value_counts()

Married     4687
Single      3943
Unknown      749
Divorced     748
Name: Marital_Status, dtype: int64

In [6]:
df.Income_Category.value_counts()

Less than $40K    3561
$40K - $60K       1790
$80K - $120K      1535
$60K - $80K       1402
Unknown           1112
$120K +            727
Name: Income_Category, dtype: int64

In [7]:
df.Attrition_Flag.value_counts()

Existing Customer    8500
Attrited Customer    1627
Name: Attrition_Flag, dtype: int64

In [8]:
df.Gender.value_counts()

F    5358
M    4769
Name: Gender, dtype: int64

In [9]:
## Unknown이 없는 열은 모두 1과 0으로 바꾼 후 진행

df['Attrition_Flag'] = np.where(df['Attrition_Flag'] == 'Existing Customer', 0, 1)
df['Gender'] = np.where(df['Gender']=="F",0, 1)

In [12]:
## Unknown이 있는 열은 모두 제거 한 데이터로 진행

train_df = df.copy()

train_df = pd.concat([ train_df, pd.get_dummies( train_df['Education_Level']).drop(columns=['Unknown'])], axis=1)
train_df = pd.concat([ train_df, pd.get_dummies( train_df['Income_Category']).drop(columns=['Unknown'])], axis=1)
train_df = pd.concat([ train_df, pd.get_dummies( train_df['Marital_Status']).drop(columns=['Unknown'])], axis=1)
train_df = pd.concat([ train_df, pd.get_dummies( train_df['Card_Category'])], axis=1)

 ## get_dummies를 이용해 더미화 시킨 후 이후 해당 열 제거
train_df.drop(columns = ['Education_Level', 'Income_Category', 'Marital_Status', 'Card_Category'], inplace=True)
train_df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,...,$60K - $80K,$80K - $120K,Less than $40K,Divorced,Married,Single,Blue,Gold,Platinum,Silver
0,768805383,0,45,1,3,39,5,1,3,12691.0,...,1,0,0,0,1,0,1,0,0,0
1,818770008,0,49,0,5,44,6,1,2,8256.0,...,0,0,1,0,0,1,1,0,0,0
2,713982108,0,51,1,3,36,4,1,0,3418.0,...,0,1,0,0,1,0,1,0,0,0
3,769911858,0,40,0,4,34,3,4,1,3313.0,...,0,0,1,0,0,0,1,0,0,0
4,709106358,0,40,1,3,21,5,1,0,4716.0,...,1,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,0,50,1,2,40,3,2,3,4003.0,...,0,0,0,0,0,1,1,0,0,0
10123,710638233,1,41,1,2,25,4,2,3,4277.0,...,0,0,0,1,0,0,1,0,0,0
10124,716506083,1,44,0,1,36,5,3,4,5409.0,...,0,0,1,0,1,0,1,0,0,0
10125,717406983,1,30,1,2,36,4,3,3,5281.0,...,0,0,0,0,0,0,1,0,0,0
10126,714337233,1,43,0,2,25,6,2,4,10388.0,...,0,0,1,0,1,0,0,0,0,1

In [14]:
train_df.isna().sum().sum()

## 최종 결측치 - 0

0

In [28]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=['Attrition_Flag'])
y = train_df['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [29]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8101, 36), (2026, 36), (8101,), (2026,))

In [30]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
import time

In [31]:
## 모형 적합

### RandomForest
rf_clf = RandomForestClassifier()
start = time.time()
rf_clf.fit(X_train, y_train)
end = time.time()

## 결과 파악
y_pred = rf_clf.predict(X_test)

print("소요 시간 : ", end - start)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred))

소요 시간 :  1.0213158130645752
Accuracy :  1.0
Recall score:  1.0

In [32]:
## 모형 적합

### AdaBoost
ada_clf = AdaBoostClassifier()
start = time.time()
ada_clf.fit(X_train, y_train)
end = time.time()

## 결과 파악
y_pred = ada_clf.predict(X_test)

print("소요 시간 : ", end - start)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred))

소요 시간 :  0.03016829490661621
Accuracy :  1.0
Recall score:  1.0

In [33]:
## 모형 적합

### XGBoost
xgb_clf = XGBClassifier()
start = time.time()
xgb_clf.fit(X_train, y_train)
end = time.time()

## 결과 파악
y_pred = xgb_clf.predict(X_test)

print("소요 시간 : ", end - start)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred))

소요 시간 :  0.37621521949768066
Accuracy :  1.0
Recall score:  1.0

In [35]:
'''
데이터가 좋은건지 추가적인 전처리가 없어도 Acc가 1.0이 나오는 게 당황스럽지만 이로 인해 별 다른 처리 없이 제출합니다 :)
'''

'\n데이터가 좋은건지 추가적인 전처리가 없어도 Acc가 1.0이 나오는 게 당황스럽지만 이로 인해 별 다른 처리 없이 제출합니다 :)\n'